---
# tasks file for ansible-role-arc-client
#
#
- name: Print fgci_install
  ansible.builtin.debug:
    var: fgci_install
    verbosity: 1

- name: Remove ARC5 client packages
  ansible.builtin.yum:
    name: "{{ arc5_client_packages }}"
    state: absent

- name: Remove ARC5 key
  ansible.builtin.rpm_key:
    state: absent
    key: 240a5db2

- name: Install nordugrid repo
  ansible.builtin.yum:
    pkg: "https://download.nordugrid.org/packages/nordugrid-release/releases/6/centos/el7/x86_64/nordugrid-release-6-1.el7.noarch.rpm"
    state: present

- name: Install nordugrid rpm key
  ansible.builtin.rpm_key:
    key: https://download.nordugrid.org/RPM-GPG-KEY-nordugrid-6
    state: present

- name: Check if there's a nordugrid.repo.rpmnew
  ansible.builtin.stat:
    path: /etc/yum.repos.d/nordugrid.repo.rpmnew
  register: arc_frontend_rpmnew_stat

- name: Replace old nordugrid.repo
  ansible.builtin.command: mv /etc/yum.repos.d/nordugrid.repo.rpmnew /etc/yum.repos.d/nordugrid.repo
  when: arc_frontend_rpmnew_stat.stat.exists

- name: Install packages for arc-client
  ansible.builtin.yum:
    pkg: "{{ arc6_client_packages }}"
    state: present

- name: Template in fetch-crl.d config
  ansible.builtin.template:
    src: fetch-crl.conf
    dest: /etc/fetch-crl.d/proxy.conf
    mode: 0644
    owner: root
    group: root
    backup: false

- name: Start fetch-crl-cron
  ansible.builtin.service:
    name: fetch-crl-cron
    state: started
    enabled: true
  when: ansible_connection != 'chroot'

- name: Enable fetch-crl-cron in chroot
  ansible.builtin.command: systemctl enable fetch-crl-cron # noqa command-instead-of-module
  when: ansible_connection == 'chroot'

- name: Add EGI Trustanchors repository
  ansible.builtin.get_url:
    url: "http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo"
    dest: /etc/yum.repos.d/egi-trustanchors.repo
    mode: 0644
    owner: root
  when: repo_egi_trustanchors | bool

- name: Install repo_egi_packages
  ansible.builtin.yum:
    name: "{{ repo_egi_packages }}"
    state: present
  when: repo_egi_trustanchors | bool

- name: Check if there's a nordugrid-updates.repo
  ansible.builtin.stat:
    path: /etc/yum.repos.d/nordugrid-updates.repo
  register: arc_frontend_excludecas

- name: Exclude IGTF CAs from Nordugrid repo
  ansible.builtin.ini_file:
    dest: /etc/yum.repos.d/nordugrid-updates.repo
    section: nordugrid-updates
    option: exclude
    value: ca_*
    no_extra_spaces: true
    owner: "root"
    group: "root"
    mode: 0644
    backup: true
  when: arc_frontend_excludecas.stat.exists

- name: Template ARC client.conf
  ansible.builtin.template:
    src: client.conf.j2
    dest: /etc/arc/client.conf
    owner: root
    group: root
    mode: 0644
  when: arc_client_conf | bool
